### ISSUE TITLE
Request: Apache 2.0 license on project

### ISSUE THREAD

**Issue by RoundSparrow** [jmarranz/itsnat#1]
Hi,

your newsgroup announcement said Apache 2.0 - but Github does not. Can you please update?

**Comment by jmarranz** [comment]
On 29/03/2015 22:21, Stephen Gutknecht wrote:

> Hi,
> 
> your newsgroup announcement said Apache 2.0 - but Github does not. Can 
> you please update?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/jmarranz/itsnat/issues/1.

Hello Stephen

ItsNat licensing is a bit more complicated:

ItsNat server (a Java web app) is LGPL v3
https://github.com/jmarranz/itsnat/blob/master/itsnat/LICENSES.txt

ItsNat Droid is Apache 2
https://github.com/jmarranz/itsnat/blob/master/ItsNatDroid/LICENSE-2.0.txt

I recognize I must change the docs to make it clearer.

Regards
Jose M. Arranz
