### ISSUE TITLE
TestApp - TEST LOCAL 1 - Pressing Reload crashes App

### ISSUE THREAD

**Issue by RoundSparrow** [jmarranz/itsnat#2]
org.itsnat.droid.ItsNatDroidException: Not equal: "38.0" - "37.5"
            at org.itsnat.itsnatdroidtest.testact.util.Assert.assertEquals(Assert.java:76)
            at org.itsnat.itsnatdroidtest.testact.local.TestLocalXMLInflate1.test(TestLocalXMLInflate1.java:132)
            at org.itsnat.itsnatdroidtest.testact.local.TestLayoutLocal1$1.onClick(TestLayoutLocal1.java:51)
1.  Works fine on Nexus 5 with Android 5.1
2. Crash above on  Sony Z Ultra GPE with Android 5.0.
   
   I think it's the unique screen size of the Sony Z Ultra that causes grief.  It has an oddball density - it comes up as one of the TV densities - not the more common ones.

**Comment by jmarranz** [comment]
It's not a serious problem, dimensions are provided in dps in my tests, is just a round problem, use Float.parseFloat and Math.round and convert again to String.

Thanks for your contribution

**Comment by jmarranz** [comment]
I think I've fixed any round problem, in theory it must work fine in any device/emulator v4.0.3 +

Anyway new issues must be registered in the new project;
https://github.com/jmarranz/itsnat_droid
