### ISSUE TITLE
TestApp - TEST LOCAL RESOURCES - Pressing Reload crashes App

### ISSUE THREAD

**Issue by RoundSparrow** [jmarranz/itsnat#3]
Nexus 5 running stock Android 5.1 and Sony Z Ultra GPE Android 5.0 both crash on this one:

```
org.itsnat.droid.ItsNatDroidException: Not equal: "108" - "72"
        at org.itsnat.itsnatdroidtest.testact.util.Assert.assertEquals(Assert.java:66)
        at org.itsnat.itsnatdroidtest.testact.util.Assert.assertEquals(Assert.java:320)
        at org.itsnat.itsnatdroidtest.testact.local.TestLocalXMLInflateResources.test(TestLocalXMLInflateResources.java:141)
        at org.itsnat.itsnatdroidtest.testact.local.TestLayoutLocalResources$1.onClick(TestLayoutLocalResources.java:40)
        at android.view.View.performClick(View.java:4780)
```

**Comment by jmarranz** [comment]
I must study this issue, be aware sometimes I must make hacks to test static vs dynamic properties, in this case is a test related to a NinePatchDrawable, comment the test in TestLocalXMLInflateResources and just visually check whether the NinePatchDrawable is correctly drawn in dynamic regarding to static.

Anyway, can you provide the other exception and the device of each exception?

**Comment by jmarranz** [comment]
ItsNat Droid has been stopped for a while but I'm going to get back again to development very soon.

**Comment by RoundSparrow** [comment]
Suggestion is to have a common method on these layout internal issues. And call that method instead of always doing an assert.  Then make an option (menu checkbox?) to not Assert and instead Toast or produce a report via (keep each errror in an ArrayList and then dump them off a menu option "View Errors").

**Comment by jmarranz** [comment]
Asserts are only useful for me as developer, when ItsNat Droid is mature I'll make a "pretty example" with no test code, now I just have a test app used for development. My recommendation for you is to comment the offending assert, because I suppose you are mainly interested on evaluating the potential uses of ItsNat Droid. 

Anyway your report is interesting to show problematic attributes to study further, I must recognize sometimes I don't understand why state defined by using an attribute is different to state defined by equivalent code.

**Comment by jmarranz** [comment]
Try again, it should be fixed, use the "development" branch, this branch is the working branch

**Comment by jmarranz** [comment]
This repository is only for itsnat_server, this includes server based capabilities for ItsNat Droid Android client.
Open a new issue in the new repository for ItsNat Droid SDK Android https://github.com/jmarranz/itsnat_droid

**Comment by jmarranz** [comment]
I think I've fixed any round problem, in theory it must work fine in any device/emulator v4.0.3 +

Anyway new issues must be registered in the new project;
https://github.com/jmarranz/itsnat_droid
