### ISSUE TITLE
Dynamically inflated layouts - all views have -1 getId() - suggest default

### ISSUE THREAD

**Issue by RoundSparrow** [jmarranz/itsnat#4]
Currently the code does this:

```
addAttrDesc(new AttrDescViewReflecMethodId(this,"id", -1));
```

Suggestion is to change this to:

```
addAttrDesc(new AttrDescViewReflecMethodId(this,"id", View.generateViewId()));
```

This requires API 17 - so  maybe do it only if the runtime is 17 or higher...

**Comment by jmarranz** [comment]
Stephen, the -1 value is correct, this is the default value used by Android when no id is defined.

Anyway do not care very much with default values, default values are only used when removing an attribute of the Android native-dynamic layout, I'm sure removing attributes will not be usual in future "ItsNat Droid" apps.

**Comment by jmarranz** [comment]
Can I close this issue?

**Comment by jmarranz** [comment]
Can you review again the other issues using the development branch to close them?

**Comment by RoundSparrow** [comment]
Yha, let's close this for now.
