### ISSUE TITLE
What is ItsNat Droid? :)

### ISSUE THREAD

**Issue by ravindranathakila** [jmarranz/itsnat#6]
Curious to know more about it!

**Comment by jmarranz** [comment]
Take a look: 
https://groups.google.com/forum/#!topic/itsnat/13nl0P12J_s

I'm going to continue development very soon, anyway many interesting are already done.

**Comment by ravindranathakila** [comment]
Thanks!

**Comment by jmarranz** [comment]
Ravin, ItsNat Droid (Android client side) has now a new README.md page in:

https://github.com/jmarranz/itsnat/tree/master/ItsNatDroid

By the way, happy birthday (offset -2 days)

**Comment by ravindranathakila** [comment]
Thanks :) Finally got about reading the github notifications! Sorry!

**Comment by jmarranz** [comment]
I've changed repository names, ItsNat Droid (Android client side) is here (including README.md):

https://github.com/jmarranz/itsnat_droid/
